# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99b6b8314ad3db8498edef8cd50ba0e4a004dcc8f88bb86bfbc86707db0b9af8f276840d87d33c2ef81f1446096a342202ac74502b2cdbf767706334b57b795

test:
  secret_key_base: c4591a4b761c6b28cc1fc49634c34b06bee89168e8b869eca8ff944d5f5861ec767411d6ff71bced9fb70fe89189283c491cee541473fb18a6a5c01beeedbd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
